FROM alpine:3.20

# Install Python and pip
RUN apk add --no-cache python3 py3-pip

# Copy your project requirements
COPY ./requirements.txt /requirements.txt

# Upgrade pip and install project dependencies
RUN pip install --upgrade pip
RUN pip install setuptools==58.0.4 wheel
RUN pip install -r /requirements.txt

# Set the working directory
WORKDIR /app

# Copy the application code
COPY . /app

# Set permissions and user
RUN addgroup -S www-data && adduser -S www-data -G www-data && \
    chown -R www-data:www-data /app

USER www-data

# Expose the application port
EXPOSE 8000

# Default command for running tests
CMD ["pytest", "--maxfail=1", "--disable-warnings"]
