FROM alpine:3.20

# Install Python, pip, and other dependencies
RUN apk add --no-cache python3 py3-pip

# Set the working directory
WORKDIR /app

# Copy the project requirements file
COPY ./requirements.txt /app/requirements.txt

# Create and activate a virtual environment, then install dependencies
RUN python3 -m venv /app/venv
RUN /app/venv/bin/pip install --upgrade pip
RUN /app/venv/bin/pip install setuptools==58.0.4 wheel
RUN /app/venv/bin/pip install -r /app/requirements.txt

# Copy the rest of the application code
COPY . /app

# Set permissions and user
RUN addgroup -S www-data && adduser -S www-data -G www-data && \
    chown -R www-data:www-data /app

USER www-data

# Expose the application port
EXPOSE 8000

# Default command
CMD ["/app/venv/bin/python", "manage.py", "runserver", "0.0.0.0:8000"]
